#ifndef __AGTB_GEODESY_PROJECTION_GAUSS_KRUGER_HPP__
#define __AGTB_GEODESY_PROJECTION_GAUSS_KRUGER_HPP__

#include "../Ellipsoid/Geometry.hpp"

AGTB_GEODESY_BEGIN

AGTB_FILE_NOT_IMPLEMENT();

AGTB_GEODESY_END

#endif